const assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const browser=await chromium.launch(), failures=[];
 async function check(name,run,init){const context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));if(init)await page.addInitScript(init);try{await run(page);assert.deepEqual(errors,[]);console.log('PASS:',name);}catch(e){failures.push(name+': '+e.message);console.error('FAIL:',name,e.message);}finally{await context.close();}}
 const visit=async(p,route)=>{await p.goto('http://localhost:3000/#/'+route);await p.waitForSelector('#mode-nav');};
 await check('editing checked choices invalidates feedback and completion',async p=>{
  await visit(p,'lesson/foundation-references/practise');await p.waitForSelector('[data-check]');
  const e=await p.evaluate(()=>ALL_LESSONS.find(l=>l.id==='foundation-references').exercises.find(e=>e.choices));
  const row=p.locator('#'+e.id);await row.locator('input[value="'+e.valid[0]+'"]').check();await row.locator('[data-check]').click();assert.match(await row.locator('.course-feedback').innerText(),/successfully/);
  const wrong=await row.locator('input').evaluateAll((els,valid)=>els.find(el=>!valid.includes(Number(el.value))).value,e.valid);await row.locator(`input[value="${wrong}"]`).check();
  assert.equal(await row.locator('.course-feedback').innerText(),'');assert.notEqual(await p.evaluate(id=>course.entry('foundation-references').answers[id]?.correct,e.id),true);
 });
 await check('editing open responses clears model review',async p=>{
  await visit(p,'lesson/ministry-01/practise');await p.waitForSelector('[data-draft]');const draft=p.locator('[data-draft]').first(),id=await draft.getAttribute('data-draft');await draft.fill('Doğru mu anladım?');await p.locator('#'+id+' [data-check]').click();await p.locator('[data-reviewed="'+id+'"]').check();await draft.fill('Yeni cevap');assert.equal(await p.locator('#feedback-'+id).innerText(),'');
 });
 await check('partial Bible study records accepted by backups render safely',async p=>{await visit(p,'bible/study/study-2co-5-17/read');await p.waitForSelector('#bible-note',{timeout:12000});assert.equal(await p.locator('#bible-note').inputValue(),'Kept note');},()=>localStorage.setItem('spiritual_turkish_device_v3',JSON.stringify({version:3,words:{},notes:{},notebookMigrated:true,bibleStudy:{entries:{'study-2co-5-17':{visited:true,notes:'Kept note'}}}})));
 await check('one damaged Bible entry preserves other notes',async p=>{await visit(p,'bible/study/study-2co-5-17/read');await p.waitForSelector('#bible-note');assert.equal(await p.locator('#bible-note').inputValue(),'Do not lose this');},()=>localStorage.setItem('spiritual_turkish_device_v3',JSON.stringify({version:3,words:{},notes:{},notebookMigrated:true,bibleStudy:{entries:{'study-2co-5-17':{notes:'Do not lose this',answers:{}},'study-gal-2-20':{notes:42}}}})));
 await check('English word search is case insensitive and causes no console errors',async p=>{await visit(p,'words');await p.waitForSelector('#word-search');await p.locator('#word-search').fill('faith');const lower=await p.locator('#view [role=status]').innerText();await p.locator('#word-search').fill('FAITH');assert.equal(await p.locator('#view [role=status]').innerText(),lower);assert(!lower.startsWith('0 '));});
 await check('saved prayer identifiers and titles remain plain text',async p=>{await visit(p,'lesson/ch5-2/read');await p.waitForSelector('#saved-prayers-list button');assert.equal(await p.locator('#saved-prayers-list [data-audit]').count(),0);await p.locator('#saved-prayers-list button').first().click();assert.equal(await p.locator('#assembled-tr-textarea').inputValue(),'Tanrım, yardım et.');assert.equal(await p.locator('#toast-container b').count(),0);},()=>localStorage.setItem('spiritual_turkish_prayers',JSON.stringify([{id:'x\"><b data-audit>unexpected</b><button data-x="',title:'<b>My prayer</b>',content:'Tanrım, yardım et.'}])));
 await check('custom syllables render input as text',async p=>{await visit(p,'lesson/ch1-2/read');await p.waitForSelector('#custom-syllable-input',{state:'visible'});await p.locator('#custom-syllable-input').fill('<b>xx</b>');await p.locator('#custom-syllable-btn').click();assert.equal(await p.locator('#custom-syllable-result b').count(),0);});
 await check('unavailable clipboard provides feedback without exceptions',async p=>{await visit(p,'lesson/ch5-2/read');await p.waitForSelector('#assembled-tr-textarea',{state:'visible'});await p.locator('#assembled-tr-textarea').fill('Tanrım, yardım et.');await p.locator('#copy-prayer-btn').click();await p.waitForSelector('#toast-container');assert.match(await p.locator('#toast-container').innerText(),/clipboard|copy/i);},()=>Object.defineProperty(navigator,'clipboard',{value:undefined,configurable:true}));
 await check('denied clipboard also handles dynamically rendered library copy',async p=>{await visit(p,'lesson/ch5-3/read');await p.waitForSelector('[data-copy-text]',{state:'visible'});await p.locator('[data-copy-text]').first().click();await p.waitForSelector('#toast-container');assert.match(await p.locator('#toast-container').innerText(),/denied/);},()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:()=>Promise.reject(new Error('Denied'))},configurable:true}));
 await check('dynamic workshop speech plays exactly once',async p=>{await visit(p,'lesson/ch1-2/read');await p.waitForSelector('#custom-syllable-input',{state:'visible'});await p.locator('#custom-syllable-input').fill('Hristiyan');await p.locator('#custom-syllable-btn').click();await p.locator('#custom-syllable-result [data-speech]').click();assert.deepEqual(await p.evaluate(()=>window.auditSpoken),['Hristiyan']);},()=>{window.auditSpoken=[];window.SpeechSynthesisUtterance=class{constructor(text){this.text=text;}};Object.defineProperty(window,'speechSynthesis',{value:{getVoices:()=>[{lang:'tr-TR'}],cancel(){},speak(u){window.auditSpoken.push(u.text);u.onstart?.();u.onend?.();}}});});
 await check('changing activity aborts pending recognition and resets mic controls',async p=>{await visit(p,'lesson/ch1-4/read');await p.waitForSelector('#mic-record-btn',{state:'visible'});await p.locator('#mic-record-btn').click();assert.equal(await p.evaluate(()=>audioEngine.isListening),true);await p.locator('#mode-nav [data-mode=words]').click();await p.waitForSelector('#word-search');assert.equal(await p.evaluate(()=>window.auditAborts),1);assert.equal(await p.evaluate(()=>audioEngine.isListening),false);await p.locator('#mode-nav [data-mode=practice]').click();await p.waitForSelector('#mic-record-btn',{state:'visible'});assert.equal(await p.locator('#mic-record-btn.mic-recording').count(),0);},()=>{window.auditAborts=0;window.SpeechRecognition=class{start(){}abort(){window.auditAborts++;}};});
 await check('speech API exceptions leave the site and fallback usable',async p=>{await visit(p,'lesson/foundation-references/read');await p.waitForSelector('[data-play-all]');await p.locator('[data-play-all]').click();assert.match(await p.locator('#course-audio-status').innerText(),/No Turkish|unavailable|could not/i);await p.locator('#mode-nav [data-mode=words]').click();await p.waitForSelector('#word-search');},()=>{Object.defineProperty(window,'speechSynthesis',{value:{getVoices(){throw Error('Blocked');},cancel(){throw Error('Blocked');}}});window.SpeechRecognition=class{constructor(){throw Error('Blocked');}};});
 await check('vowel-loss answers stay text and labelled after checking',async p=>{await visit(p,'lesson/ch4-2/read');await p.waitForSelector('#unlu-input-1',{state:'visible'});const input=p.locator('#unlu-input-1');await input.fill('\" data-audit=\"injected');await p.locator('#unlu-quiz-container button').first().click();assert.equal(await p.locator('#unlu-quiz-container [data-audit]').count(),0);assert(await input.getAttribute('aria-label'));});
 await check('flip-card meanings are keyboard accessible with inactive side hidden',async p=>{await visit(p,'lesson/ch4-3/read');await p.waitForSelector('#flip-cards-container',{state:'visible'});const b=p.locator('#flip-cards-container [data-flip-card="0"]:not([inert] *)');await b.focus();await p.keyboard.press('Enter');assert.match(await b.innerText(),/everyday/);assert.equal(await p.evaluate(()=>document.activeElement.dataset.flipCard),'0');assert.equal(await p.locator('#flip-cards-container .flipped [inert]').count(),1);await p.keyboard.press('Space');assert.match(await b.innerText(),/Christian/);});
 await check('retry preserves other answers and original draft',async p=>{await visit(p,'lesson/ministry-01/practise');await p.waitForSelector('[data-check]');const es=await p.evaluate(()=>ALL_LESSONS.find(l=>l.id==='ministry-01').exercises.filter(e=>e.choices));await p.locator(`#${es[0].id} input`).first().check();await p.locator(`#${es[1].id} input`).first().check();await p.locator('#course-response').fill('Özgün yanıt.');await p.locator(`#${es[0].id} [data-retry]`).click();assert.equal(await p.locator(`#${es[1].id} input:checked`).count(),1);assert.equal(await p.locator('#course-response').inputValue(),'Özgün yanıt.');});
 await check('Turkish uppercase answers grade correctly and edits clear feedback',async p=>{await visit(p,'lesson/ch4-2/read');await p.waitForSelector('#unlu-input-1',{state:'visible'});const q=await p.evaluate(()=>APP_DATA.syntax.unluDusmesiQuiz.find(q=>q.correctAnswer.includes('ı')));const input=p.locator('#unlu-input-'+q.id);await input.fill(q.correctAnswer.toLocaleUpperCase('tr-TR'));await p.locator(`button[onclick="checkUnluAnswer(${q.id})"]`).click();assert.match(await p.locator('#unlu-feedback-'+q.id).innerText(),/Correct/);await input.fill('Changed');assert.equal(await p.locator('#unlu-feedback-'+q.id).innerText(),'');});
 await check('unknown Bible links explain missing content and offer recovery',async p=>{for(const path of ['bible/study/study-missing-1-1/read','bible/topic/missing']){await visit(p,path);await p.waitForSelector('#page-heading');assert.match(await p.locator('#page-heading').innerText(),/not found/);assert.equal(await p.locator('#bible-load-retry').count(),0);await p.locator('#view [href="#/bible"]').last().click();await p.waitForSelector('#bible-results');}});
 await check('unavailable storage saves prayer in session with honest feedback',async p=>{await visit(p,'lesson/ch5-2/read');await p.waitForSelector('#assembled-tr-textarea',{state:'visible'});await p.locator('#assembled-tr-textarea').fill('Beni bağışla.');p.on('dialog',d=>d.accept('Session prayer'));await p.locator('#save-prayer-btn').click();await p.waitForSelector('#toast-container');assert.match(await p.locator('#toast-container').innerText(),/session only/);assert.match(await p.locator('#saved-prayers-list').innerText(),/Session prayer/);assert.match(await p.evaluate(()=>learningStore.export().values.spiritual_turkish_prayers),/Session prayer/);},()=>{Storage.prototype.setItem=function(){throw Error('Unavailable');};});
 await check('damaged saved-word records do not break the review or discard notes',async p=>{await visit(p,'words/review');await p.waitForSelector('#view h1');assert.equal(await p.evaluate(()=>deviceLearning.state.notes['prayer-draft']),'Personal text');assert.equal(await p.evaluate(()=>Object.keys(deviceLearning.state.words).length),2);},()=>localStorage.setItem('spiritual_turkish_device_v3',JSON.stringify({version:3,words:{bad:null,another:{due:'invalid',step:99,legacy:{word:'Personal word',meaning:'Kept meaning'}}},notes:{'prayer-draft':'Personal text'},notebookMigrated:true})));
 await check('malformed optional lesson containers preserve original response',async p=>{await visit(p,'lesson/foundation-references/read');await p.waitForSelector('#course-title');assert.equal(await p.locator('#course-response').inputValue(),'Özgün not.');await p.locator('[data-check]').last().click();assert.match(await p.locator('.course-feedback').last().innerText(),/response first/);},()=>localStorage.setItem('spiritual_turkish_learning_v2',JSON.stringify({version:2,lessons:{'foundation-references':{response:'Özgün not.',answers:[],drafts:42,rubric:{}}}})));
 await check('workshop returns and corrected controls fit both languages at all widths',async p=>{await visit(p,'lesson/ch5-2/read');await p.waitForSelector('#prayer-mode-panel');assert.equal(await p.locator('#legacy-intro').evaluate(e=>getComputedStyle(e).display),'flex');for(const width of [360,390,768,1440])for(const locale of ['en','ko']){await p.setViewportSize({width,height:900});await p.selectOption('#study-language',locale);await p.waitForFunction(l=>document.documentElement.lang===l,locale);assert(await p.locator('#assembled-tr-textarea').getAttribute('aria-label'));assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}await p.locator('.in-chapter-subtab[data-subtab-id="ch5-3"]').click();await p.waitForSelector('[data-copy-text]',{state:'visible'});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));});
 await browser.close();if(failures.length){console.error(failures.join('\n'));process.exit(1);}
})().catch(e=>{console.error(e);process.exit(1);});
