const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.join(__dirname,'..'),folder=path.join(root,'content/bible-study');
const read=file=>JSON.parse(fs.readFileSync(path.join(folder,file),'utf8'));
const manifest=read('manifest.json'),scripture=read('scripture.json'),lessons=manifest.passages.map(p=>read(p.file));
const c={};c.window=c;vm.createContext(c);for(const file of ['data.js','lessons.js','editorial-data.js','source-curriculum.js','prayer-curriculum.js','context-curriculum.js','reading-curriculum.js','curriculum-index.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),c);
const bilingual=(v,label)=>{assert.equal(typeof v?.en,'string',label);assert.equal(typeof v?.ko,'string',label);assert(v.en.trim()&&v.ko.trim(),label);assert(!/[\p{Script=Hangul}\uFFFD]/u.test(v.en),label+' English leakage');};
test('Bible collection equals the canonical 60-reference fixture and counts selected versus quoted verses',()=>{
 const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/bible-study-references.json')));
 assert.deepEqual(manifest.passages.map(p=>p.sourceSelection.reference),fixture.references);assert.equal(manifest.passages.length,60);assert.equal(new Set(manifest.passages.map(p=>p.id)).size,60);assert.equal(manifest.categories.length,5);assert.equal(manifest.topics.length,30);
 const selected=new Set(manifest.passages.flatMap(p=>p.verseIds)),quoted=new Set(Object.values(scripture.verses).flatMap(v=>v.numberedVerseIds));assert.equal(selected.size,74);assert.equal(quoted.size,77);assert(!selected.has('PSA.119.10'));assert(!quoted.has('PSA.119.10'));assert(quoted.has('HEB.9.28')&&quoted.has('TIT.3.4')&&quoted.has('TIT.3.6'));
 for(const category of manifest.categories){assert.equal(manifest.passages.filter(p=>p.categoryId===category.id).length,12);assert.equal(manifest.topics.filter(p=>p.categoryId===category.id).length,6);}
 assert.deepEqual(manifest.counts,{initialPassages:60,canonicalNumberedVerses:74,quotedNumberedVerses:77});assert.equal(c.ALL_LESSONS.length,77);assert.equal(c.SEMINAR.passages.length,82);
});
test('Scripture has exact frozen source fingerprints, numbered units, provenance, and no script corruption',()=>{
 const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/bible-study-scripture-hashes.json')));
 assert.equal(scripture.edition.id,'TCL02');assert.equal(scripture.edition.quotationLimit,100);assert.match(scripture.edition.copyright,/Kitabı Mukaddes Şirketi.*2001, 2008/);
 for(const[id,v]of Object.entries(scripture.verses)){assert.equal(v.id,id);assert(v.text.length>20);assert(!/[\p{Script=Hangul}\p{Script=Han}\p{Script=Cyrillic}\p{Script=Ethiopic}\uFFFD]/u.test(v.text));const hash=crypto.createHash('sha256').update(v.text).digest('hex');assert.equal(hash,fixture[id]);assert.equal(hash,v.sha256);assert(v.numberedVerseIds.includes(id));assert.equal(v.editionId,'TCL02');assert.match(v.source,/^https:\/\/www\.bible\.com\/bible\/170\//);assert(v.verification&&v.verifiedOn);}
 for(const p of manifest.passages){assert.equal(p.editionId,'TCL02');assert(p.verseIds.every(id=>scripture.verses[id]));for(const lang of ['tr','en','ko'])assert(p.reference.displayNames[lang]);}
});
test('All 60 curated lessons have complete teaching, valid occurrence spans, morphology, and explained exercises',()=>{
 const ids=new Set(),lessonIds=new Set(c.ALL_LESSONS.map(l=>l.id)),readingIds=new Set(c.SEMINAR.passages.map(l=>l.id));
 for(const a of lessons){const p=manifest.passages.find(p=>p.id===a.id);for(const key of ['objective','prerequisites','naturalMeaning','independentTask','selfAssessment'])bilingual(a[key],a.id+'.'+key);assert(a.clauses.length>=1&&a.grammar.length>=2&&a.analyses.length>=4&&a.vocabulary.length>=3);bilingual(a.modelResponse.meaning,a.id);assert(a.modelResponse.tr.length>10);
  for(const id of p.verseIds)assert(a.clauses.some(clause=>clause.sourceSpans.some(s=>s.verseId===id)),a.id+' missing verse teaching');
  for(const clause of a.clauses){for(const key of ['naturalMeaning','literalGloss','explanation'])bilingual(clause[key],clause.id);for(const s of clause.sourceSpans){assert(p.verseIds.includes(s.verseId));assert(s.start>=0&&s.end<=scripture.verses[s.verseId].text.length&&s.end>s.start);}}
  for(const w of a.analyses){assert(!ids.has(w.id));ids.add(w.id);const source=scripture.verses[w.verseId].text;assert(p.verseIds.includes(w.verseId));assert.equal(source.slice(w.start,w.end),w.surface);assert(!/\p{L}/u.test(source[w.start-1]||''));assert(!/\p{L}/u.test(source[w.end]||''));assert.equal(w.segments.map(s=>s.form).join(''),w.surface);for(const key of ['meaning','dictionaryMeaning','partOfSpeech','role','contextualExplanation'])bilingual(w[key],w.id);for(const s of w.segments)bilingual(s.meaning,w.id);for(const s of w.stemChanges)bilingual(s,w.id);}
  const ordered=[...a.analyses].sort((x,y)=>x.verseId.localeCompare(y.verseId)||x.start-y.start);for(let i=1;i<ordered.length;i++)if(ordered[i].verseId===ordered[i-1].verseId)assert(ordered[i].start>=ordered[i-1].end,'overlapping '+a.id);
  for(const g of a.grammar){bilingual(g.title,g.id);bilingual(g.explanation,g.id);assert(g.relatedLessonIds.every(id=>lessonIds.has(id)));}
  for(const v of a.vocabulary){bilingual(v.definitions,v.id);bilingual(v.usageNotes,v.id);assert(a.analyses.some(w=>w.id===v.analysisId));assert(['general','biblical','literary'].includes(v.classification));}
  assert(a.relatedLessonIds.every(id=>lessonIds.has(id)));assert(a.relatedReadingIds.every(id=>readingIds.has(id)));assert.equal(a.exercises.length,4);assert.equal(a.exercises[0].type,'reference-to-passage');assert.equal(a.exercises[1].type,'passage-to-reference');
  for(const e of a.exercises){assert(!ids.has(e.id));ids.add(e.id);bilingual(e.prompt,e.id);bilingual(e.explanations,e.id);assert(e.options.length>=3);assert.equal(new Set(e.options.map(o=>o.id)).size,e.options.length);assert(e.acceptedOptionIds.length>=1&&e.acceptedOptionIds.every(id=>e.options.some(o=>o.id===id)));for(const o of e.options){bilingual(o.explanation,e.id);if(o.label)bilingual(o.label,e.id);if(o.passageId||o.referenceId)assert(manifest.passages.some(p=>p.id===(o.passageId||o.referenceId)));}if(e.type==='reference-to-passage')assert.equal(e.options.find(o=>e.acceptedOptionIds.includes(o.id)).passageId,a.id);if(e.type==='passage-to-reference')assert.equal(e.options.find(o=>e.acceptedOptionIds.includes(o.id)).referenceId,a.id);}
 }
});
test('Bible state migration, atomic backup validation, collision preservation, and session fallback',()=>{
 const data=new Map(),storage={getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)},env={ALL_LESSONS:c.ALL_LESSONS,SEMINAR:c.SEMINAR,localStorage:storage};env.window=env;vm.createContext(env);
 const key='spiritual_turkish_device_v3',old={version:3,words:{},notes:{'prayer-draft':'Old prayer'},studyLast:{id:'foundation-references',section:'understand'},notebookMigrated:true};storage.setItem(key,JSON.stringify(old));vm.runInContext(fs.readFileSync(path.join(root,'learning-store.js'),'utf8'),env);assert.equal(env.deviceLearning.state.studyLast.id,'foundation-references');assert.equal(env.deviceLearning.state.bibleStudy.last,null);
 const incoming={...old,bibleStudy:{last:{id:manifest.passages[0].id,section:'use'},entries:{[manifest.passages[0].id]:{visited:true,practised:false,studied:false,notes:'Imported notes',section:'use',answers:{}}}}};
 const backup={format:'spiritual-turkish-device-backup',version:1,values:{[key]:JSON.stringify(incoming)}};env.learningStore.import(backup);assert.equal(env.learningStore.get(key).notes['prayer-draft'],'Old prayer');assert.equal(env.learningStore.get(key).bibleStudy.entries[manifest.passages[0].id].studied,false);
 const before=storage.getItem(key);incoming.bibleStudy.entries[manifest.passages[0].id].studied='yes';assert.throws(()=>env.learningStore.import({...backup,values:{[key]:JSON.stringify(incoming)}}));assert.equal(storage.getItem(key),before);
 const blocked=new env.LearningStore({getItem(){throw Error('blocked');},setItem(){throw Error('blocked');}});blocked.set('test',{notes:'kept'});assert.equal(blocked.get('test').notes,'kept');assert.equal(blocked.available,false);
});
