/* Run against node server.js. PLAYWRIGHT_MODULE can point to a bundled Playwright installation. */
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async()=>{
 const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[],missing=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('response',r=>{if(r.status()>=400)missing.push([r.status(),r.url()]);});
 await page.goto('http://localhost:3000');await page.waitForFunction(()=>window.selectLesson&&document.querySelector('#course-title'));
 const setLanguage=async lang=>{if((await page.evaluate(()=>innerWidth))<1024 && await page.locator('#sidebar').evaluate(el=>el.inert))await page.locator('#sidebar-toggle-btn').click();await page.selectOption('#teaching-language',lang);};
 const original={id:'saved-before-upgrade',title:'기존 기도 <script>',content:'Göksel Babam, sana şükrediyorum.',createdAt:'2026-09-30'};
 await page.evaluate(original=>{localStorage.setItem('spiritual_turkish_prayers',JSON.stringify([original]));},original);await page.reload();
 assert.equal(await page.locator('html').getAttribute('lang'),'en');
 const ids=await page.evaluate(()=>EXPANDED_LESSONS.map(l=>l.id));
 for(const lang of ['en','ko']){
   await setLanguage(lang);
   for(const id of ids){await page.evaluate(id=>selectLesson(id),id);assert(await page.locator('#course-title').isVisible());assert.equal(await page.locator('#section-ch7 fieldset').count(),3);assert.equal(await page.locator('#section-ch7 [data-rubric]').count(),5);assert.equal(await page.locator('#section-ch7 .course-dialogue li').count(),await page.evaluate(id=>EXPANDED_LESSONS.find(l=>l.id===id).lines.length,id));assert.equal(await page.evaluate(id=>course.entry(id).completed||false,id),false);const details=page.locator('#section-ch7 details').first();await details.locator('summary').press('Enter');assert.equal(await details.evaluate(el=>el.open),false);await details.locator('summary').press('Enter');assert.equal(await details.evaluate(el=>el.open),true);}
 }
 await setLanguage('en');await page.evaluate(()=>selectLesson('ministry-01'));
 // Incorrect -> explained feedback -> retry -> successful answer.
 await page.locator('#ministry-01-exercise-1 input[value="1"]').check();await page.locator('[data-check="0"]').click();assert.match(await page.locator('#feedback-ministry-01-exercise-1').innerText(),/Try again/);assert.equal(await page.evaluate(()=>course.entry('ministry-01').completed||false),false);
 await page.locator('[data-retry="0"]').click();await page.locator('#ministry-01-exercise-1 input[value="0"]').check();await page.locator('[data-check="0"]').click();await page.locator('#ministry-01-exercise-2 input[value="0"]').check();await page.locator('[data-check="1"]').click();
 await page.locator('[data-draft]').fill('Cumartesi görüşeceğiz. Doğru mu anladım?');await page.locator('[data-check="2"]').click();await page.locator('[data-reviewed]').check();
 await page.locator('#course-complete').click();assert.match(await page.locator('#course-completion-status').innerText(),/Keep practising/);
 await page.locator('#course-response').fill('Tekrar eder misiniz? Cumartesi mi? Doğru mu anladım?');for(let i=0;i<5;i++)await page.selectOption('#rubric-'+i,'2');await page.locator('#course-independent').check();await page.locator('#course-complete').click();assert.equal(await page.evaluate(()=>course.entry('ministry-01').completed),true);assert.match(await page.locator('#section-ch7 .course-kicker').innerText(),/Completed/);
 await page.reload();await page.evaluate(()=>selectLesson('ministry-01'));assert.equal(await page.locator('#course-response').inputValue(),'Tekrar eder misiniz? Cumartesi mi? Doğru mu anladım?');assert.equal(await page.evaluate(()=>course.entry('ministry-01').completed),true);
 await setLanguage('ko');assert.equal(await page.locator('#course-response').inputValue(),'Tekrar eder misiniz? Cumartesi mi? Doğru mu anladım?');await page.reload();assert.equal(await page.locator('html').getAttribute('lang'),'ko');
 await setLanguage('en');
 // Turkish alternatives in hospitality exercise both accepted.
 await page.evaluate(()=>selectLesson('ministry-02'));for(const answer of [0,1]){await page.locator('#ministry-02-exercise-2 input[value="'+answer+'"]').check();await page.locator('[data-check="1"]').click();assert.match(await page.locator('#feedback-ministry-02-exercise-2').innerText(),/Reviewed successfully/);}
 // Retained workshops all reachable and language switching is safe.
 const legacy=await page.evaluate(()=>Array.from(document.querySelectorAll('[data-lesson-id^="ch"]')).map(b=>b.dataset.lessonId));
 for(const lang of ['en','ko']){await setLanguage(lang);for(const id of legacy){await page.evaluate(id=>selectLesson(id),id);assert(await page.locator('#section-'+id.split('-')[0]).isVisible());}}
 await page.evaluate(()=>selectLesson('ch5-2'));await setLanguage('en');await page.locator('#saved-prayers-list button').first().click();assert.equal(await page.locator('#assembled-tr-textarea').inputValue(),original.content);await setLanguage('ko');assert.equal(await page.locator('#assembled-tr-textarea').inputValue(),original.content);assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('spiritual_turkish_prayers'))),[original]);
 await setLanguage('en');await page.evaluate(()=>selectLesson('ch2-2'));assert.equal(await page.locator('.simulator-choice').count(),3);await page.locator('.simulator-choice > button').first().click();assert.equal(await page.evaluate(()=>course.entry('ch2-2').completed||false),false);
 // Special-character insertion changes a persisted draft once (not twice).
 await page.evaluate(()=>selectLesson('ministry-02'));await page.locator('#course-response').fill('c');await page.locator('#course-response').focus();await page.locator('[data-insert-char="ş"]').click();assert.equal(await page.locator('#course-response').inputValue(),'cş');assert.equal(await page.evaluate(()=>course.entry('ministry-02').response),'cş');
 // Natural branch rehearsal stores practice but never completion.
 await page.evaluate(()=>selectLesson('ministry-03'));for(const type of ['clarify','accept','uncertain','refuse']){await page.selectOption('#ministry-03-branch-type',type);await page.locator('[data-branch-answer="0"]').click();assert.match(await page.locator('#branch-feedback').innerText(),/Appropriate response/);}assert.equal(await page.evaluate(()=>course.entry('ministry-03').completed||false),false);
 // Synthetic playback passes Turkish text, language and chosen rate to the browser.
 await page.evaluate(()=>{window.SpeechSynthesisUtterance=class{constructor(text){this.text=text;}};speechSynthesis.getVoices=()=>[{lang:'tr-TR',name:'Test synthetic voice'}];speechSynthesis.speak=u=>{window.lastUtterance={text:u.text,lang:u.lang,rate:u.rate};u.onstart?.();u.onend?.();};});await page.selectOption('#course-rate','0.8');await page.locator('[data-play="0"]').click();assert.equal(await page.evaluate(()=>lastUtterance.lang),'tr-TR');assert.equal(await page.evaluate(()=>lastUtterance.rate),0.8);assert.equal(await page.evaluate(()=>lastUtterance.text),await page.evaluate(()=>EXPANDED_LESSONS[2].lines[0].tr));await page.locator('[data-stop]').click();assert.match(await page.locator('#course-audio-status').innerText(),/Stopped/);
 // Safe fallbacks with no installed Turkish voice and no API.
 await page.evaluate(()=>{selectLesson('ministry-03');speechSynthesis.getVoices=()=>[];});await page.locator('[data-play="0"]').click();assert.match(await page.locator('#course-audio-status').textContent(),/No Turkish synthetic voice/);
 await page.evaluate(()=>{Object.defineProperty(window,'speechSynthesis',{value:undefined,configurable:true});delete window.speechSynthesis;});await page.locator('[data-play="0"]').click();assert.match(await page.locator('#course-audio-status').textContent(),/unavailable/);
 await page.evaluate(()=>selectLesson('ch5-2'));await page.locator('#speak-prayer-btn').click();assert.match(await page.locator('#global-audio-status').innerText(),/unavailable/);assert(await page.locator('#global-audio-status').isVisible());
 // Reload with legacy progress: imported visits must never become completed.
 await page.evaluate(()=>{localStorage.removeItem('spiritual_turkish_learning_v2');localStorage.setItem('spiritual_turkish_progress',JSON.stringify({completedLessons:['ch1-1','ministry-01']}));});await page.reload();assert.equal(await page.evaluate(()=>course.entry('ch1-1').visited),true);assert.equal(await page.evaluate(()=>course.entry('ch1-1').completed||false),false);assert.equal(await page.evaluate(()=>course.entry('ministry-01').completed||false),false);
 // Keyboard mobile menu: focus enters it, closes on Escape and returns to its opener.
 await page.setViewportSize({width:390,height:844});await page.locator('#sidebar-toggle-btn').focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.id),'teaching-language');await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.id),'sidebar-toggle-btn');assert.equal(await page.locator('#sidebar').evaluate(el=>el.inert),true);
 // Mobile menu, lesson focus and no horizontal overflow across the new flow.
 for(const width of [375,390,768,1440]){await page.setViewportSize({width,height:900});for(const lang of ['en','ko']){await setLanguage(lang);for(const id of ids){await page.evaluate(id=>selectLesson(id),id);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false,`${width}/${lang}/${id} overflow`);} } }
 await page.setViewportSize({width:390,height:844});await setLanguage('ko');await page.evaluate(()=>selectLesson('ministry-04'));await page.waitForTimeout(400);const dir=process.env.SCREENSHOT_DIR;if(dir){fs.mkdirSync(dir,{recursive:true});await page.screenshot({path:path.join(dir,'phone-ko.png'),fullPage:true});await page.setViewportSize({width:1440,height:1000});await setLanguage('en');await page.evaluate(()=>selectLesson('ministry-09'));await page.waitForTimeout(400);await page.screenshot({path:path.join(dir,'desktop-en.png'),fullPage:true});}
 assert.deepEqual(errors,[],'Unexpected browser errors');assert.deepEqual(missing,[],'Missing/failed assets');console.log('PASS: 10 lessons / 2 languages / 4 widths; feedback, retry, alternatives, rubric completion, reload, migration, saved prayers, 24 workshops, TTS fallback; no browser errors or failed assets.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
