const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],missing=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('response',r=>{if(r.status()>=400)missing.push(r.url());});
 await page.goto('http://localhost:3000');await page.waitForSelector('#study-language');
 const original={id:'saved-before-upgrade',title:'기도 <script>',content:'Göksel Babam, sana şükrediyorum.',createdAt:'2026-09-30'};
 await page.evaluate(o=>{localStorage.clear();localStorage.setItem('spiritual_turkish_prayers',JSON.stringify([o]));localStorage.setItem('spiritual_turkish_notebook',JSON.stringify([{word:'özel not',meaning:{en:'personal note',ko:'개인 메모'},breakdown:'my note'}]));localStorage.setItem('spiritual_turkish_progress',JSON.stringify({completedLessons:['ministry-01']}));},original);await page.reload();await page.waitForSelector('#study-language');
 const lang=async l=>{await page.selectOption('#study-language',l);assert.equal(await page.locator('html').getAttribute('lang'),l);};
 const visit=async p=>{await page.evaluate(p=>location.hash='#/'+p,p);await page.waitForTimeout(15);};
 const lesson=async(id,stage='read')=>{await visit(`lesson/${id}/${stage}`);await page.waitForFunction(({id,stage})=>document.querySelector('#course-title')?.textContent===course.text(ALL_LESSONS.find(l=>l.id===id).title)&&document.querySelector(`[data-section="${stage}"]`)?.getAttribute('aria-current')==='location',{id,stage});};
 assert.equal(await page.locator('html').getAttribute('lang'),'en');assert.equal(await page.evaluate(()=>course.entry('ministry-01').visited),true);assert.equal(await page.evaluate(()=>!!course.entry('ministry-01').completed),false);assert.equal(await page.evaluate(()=>Object.keys(deviceLearning.state.words).length),1);
 const ids=await page.evaluate(()=>ALL_LESSONS.map(l=>l.id));assert.equal(ids.length,77);
 for(const l of ['en','ko']){await lang(l);for(const id of ids){await lesson(id);assert.equal(await page.locator('.course-dialogue li').count(),await page.evaluate(id=>ALL_LESSONS.find(l=>l.id===id).lines.length,id));assert.equal(await page.locator('#section-ch7 fieldset').count(),await page.evaluate(id=>ALL_LESSONS.find(l=>l.id===id).exercises.length,id));assert.equal(await page.locator('[data-rubric]').count(),5);assert.equal(await page.evaluate(id=>!!course.entry(id).completed,id),false);}console.log(`All 77 lessons rendered in ${l}.`);}
 await lang('en');await lesson('ministry-01','practise');await page.locator('#ministry-01-exercise-1 input[value="1"]').check();await page.locator('[data-check="0"]').click();assert.match(await page.locator('#feedback-ministry-01-exercise-1').innerText(),/Try again/);await page.locator('[data-retry="0"]').click();
 for(let i=0;i<2;i++){await page.locator(`#ministry-01-exercise-${i+1} input[value="0"]`).check();await page.locator(`[data-check="${i}"]`).click();}
 await page.locator('[data-draft]').fill('Cumartesi görüşeceğiz. Doğru mu anladım?');await page.locator('[data-check="2"]').click();await page.locator('[data-reviewed]').check();await lesson('ministry-01','use');await page.locator('#course-complete').click();assert.match(await page.locator('#course-completion-status').innerText(),/Keep practising/);
 const response='Tekrar eder misiniz? Cumartesi mi? Doğru mu anladım?';await page.locator('#course-response').fill(response);for(let i=0;i<5;i++)await page.selectOption('#rubric-'+i,'2');await page.locator('#course-independent').check();await page.locator('#course-complete').click();assert.equal(await page.evaluate(()=>course.entry('ministry-01').completed),true);assert.equal(await page.locator('#study-nav [aria-current=page] .completion-mark').count(),1);await page.reload();assert.equal(await page.locator('#course-response').inputValue(),response);assert(await page.locator('#course-response').isVisible());await lang('ko');assert.equal(await page.locator('#course-response').inputValue(),response);await page.reload();assert.equal(await page.locator('html').getAttribute('lang'),'ko');await lang('en');await page.locator('#course-response').fill(response+' Lütfen.');assert.equal(await page.evaluate(()=>course.entry('ministry-01').completed),false);assert.equal(await page.locator('#study-nav [aria-current=page] .completion-mark').count(),0);
 await lesson('ministry-02','practise');for(const a of [0,1]){await page.locator(`#ministry-02-exercise-2 input[value="${a}"]`).check();await page.locator('[data-check="1"]').click();assert.match(await page.locator('#feedback-ministry-02-exercise-2').innerText(),/Reviewed successfully/);}
 await lesson('prayer-illness','practise');const e=await page.evaluate(()=>ALL_LESSONS.find(l=>l.id==='prayer-illness').exercises[0]);await page.locator(`#${e.id} input[value="${e.valid[0]}"]`).check();await page.locator('[data-check="0"]').click();assert.match(await page.locator(`#feedback-${e.id}`).innerText(),/Reviewed successfully/);
 await lesson('ministry-03','practise');for(const type of ['clarify','accept','uncertain','refuse']){await page.selectOption('#ministry-03-branch-type',type);await page.locator('[data-branch-answer="0"]').click();assert.match(await page.locator('#branch-feedback').innerText(),/Appropriate response/);}assert.equal(await page.evaluate(()=>!!course.entry('ministry-03').completed),false);
 await lesson('ministry-02','use');await page.locator('#course-response').fill('c');await page.locator('#course-response').focus();await page.locator('[data-letter="ş"]').click();assert.equal(await page.locator('#course-response').inputValue(),'cş');
 await lesson('foundation-references');const token=page.locator('.inline-word').first(),wid=await token.getAttribute('data-word');await token.focus();await page.keyboard.press('Enter');for(let i=0;i<12;i++){await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.getElementById('word-inspector').contains(document.activeElement)),true,'word dialog focus trap');}await page.locator('#save-word').click();const context=await page.locator('.word-example [lang=tr]').innerText();await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.dataset.word),wid);await visit('words/saved');await page.locator(`#view [data-word="${wid}"]`).click();assert.equal(await page.locator('.word-example [lang=tr]').innerText(),context);await page.keyboard.press('Escape');await page.reload();assert.equal(await page.evaluate(id=>deviceLearning.state.words[id].context.tr,wid),context);
 await visit('words');for(const q of ['lütuf','grace','은혜']){await page.locator('#word-search').fill(q);assert((await page.locator('.word-row').count())>0,q);}
 await visit('words/review');while(await page.locator('#reveal-word').count()){await page.locator('#reveal-word').click();await page.locator('[data-recall="remembered"]').click();}assert(await page.locator('.empty-state').isVisible());await page.evaluate(id=>{deviceLearning.state.words[id].due=Date.now()-1;deviceLearning.save();},wid);await page.reload();await page.locator('#reveal-word').click();await page.locator('[data-recall="again"]').click();assert.equal(await page.evaluate(id=>deviceLearning.state.words[id].step,wid),0);
 const readings=await page.evaluate(()=>SEMINAR.passages.map(p=>p.id));for(const id of readings){await visit('bible/'+id);assert(await page.locator('#reading-note').isVisible());assert.equal(await page.locator('.reading-text a[target="_blank"]').count(),1);}await visit('bible/reading-Yu-13-34-35');assert.equal(await page.locator('.verse-line').count(),2);await page.locator('#translation-toggle').click();assert.equal(await page.locator('.teaching-translation').first().isVisible(),false);await page.locator('#reading-note').fill('Kendi özetim: Birbirimizi sevmeliyiz.');await page.reload();assert.equal(await page.locator('#reading-note').inputValue(),'Kendi özetim: Birbirimizi sevmeliyiz.');
 const legacy=await page.evaluate(()=>Array.from(document.querySelectorAll('#legacy-host [data-lesson-id^="ch"]')).map(b=>b.dataset.lessonId));assert.equal(legacy.length,24);for(const l of ['en','ko']){await lang(l);for(const id of legacy){await visit(`lesson/${id}/read`);assert(await page.locator('#section-'+id.split('-')[0]).isVisible());}}
 await lang('en');await visit('lesson/ch1-1/read');await page.locator('[data-subtab-id="ch1-4"]').click();await page.waitForURL('**/#/lesson/ch1-4/read');await page.waitForSelector('#lesson-ch1-4:visible');await visit('lesson/ch5-2/read');await page.locator('#saved-prayers-list button').first().click();assert.equal(await page.locator('#assembled-tr-textarea').inputValue(),original.content);await lang('ko');assert.equal(await page.locator('#assembled-tr-textarea').inputValue(),original.content);assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('spiritual_turkish_prayers'))),[original]);assert.equal(await page.locator('#saved-prayers-list script').count(),0);
 await lang('en');await page.selectOption('#prayer-mode','Jesus-plural');assert.equal(await page.locator('#assembled-tr-textarea').inputValue(),original.content);await page.locator('#prayer-mode-load').click();assert.match(await page.locator('#assembled-tr-textarea').inputValue(),/^Rab İsa,/);assert.match(await page.locator('#assembled-tr-textarea').inputValue(),/dua ediyoruz/);assert.equal(await page.locator('.prayer-option-row button button').count(),0);assert(await page.locator('#ambient-toggle-btn').isVisible());await page.locator('#ambient-toggle-btn').click();assert.equal(await page.locator('#ambient-toggle-btn').getAttribute('aria-pressed'),'true');await page.locator('#ambient-toggle-btn').click();assert.equal(await page.locator('#ambient-toggle-btn').getAttribute('aria-pressed'),'false');await page.locator('#assembled-tr-textarea').fill('Rab İsa, sana güveniyoruz. Amin.');await page.reload();assert.equal(await page.locator('#assembled-tr-textarea').inputValue(),'Rab İsa, sana güveniyoruz. Amin.');
 await visit('lesson/ch4-1/read');await page.locator('#add-lexicon-btn').click();assert.equal(await page.evaluate(()=>Object.keys(deviceLearning.state.words).some(id=>SEMINAR.words.find(w=>w.id===id)?.tr==='gömüldük')),true);await visit('lesson/ch2-2/read');assert.equal(await page.locator('.simulator-choice').count(),3);await page.locator('.simulator-choice > button').first().click();assert.equal(await page.evaluate(()=>!!course.entry('ch2-2').completed),false);
 await visit('settings');const dp=page.waitForEvent('download');await page.locator('#export-backup').click();const d=await dp,backup=JSON.parse(fs.readFileSync(await d.path(),'utf8'));assert.equal(backup.format,'spiritual-turkish-device-backup');await page.locator('#import-backup').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"bad":true}')});await page.waitForFunction(()=>document.getElementById('backup-status').textContent.includes('not a valid'));assert.match(await page.locator('#backup-status').innerText(),/not a valid/);await page.locator('#import-backup').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.waitForFunction(()=>document.getElementById('backup-status').textContent.includes('Backup merged'));await page.reload();assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('spiritual_turkish_prayers'))),[original]);
 await visit('lesson/ch1-4/read');await page.evaluate(()=>{audioEngine.recognition={start(){this.onstart?.();this.onresult?.({results:[]});this.onend?.();},stop(){}};});await page.locator('#mic-record-btn').click();assert.match(await page.locator('#mic-status').innerText(),/No recognised text/);assert.equal(await page.evaluate(()=>audioEngine.calculateSimilarity('','')),0);await page.evaluate(()=>audioEngine.recognition=null);await page.locator('#mic-record-btn').click();assert.match(await page.locator('#mic-status').innerText(),/unavailable/);
 await visit('settings');await page.locator('#sound-effects').uncheck();await page.selectOption('#default-rate','0.8');await page.reload();assert.equal(await page.locator('#sound-effects').isChecked(),false);assert.equal(await page.locator('#default-rate').inputValue(),'0.8');
 await lesson('ministry-04');await page.locator('.skip-link').focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.id),'study-main');assert.match(page.url(),/#\/lesson\/ministry-04\/read/);await page.locator('#open-outline').click();await page.locator('#outline-dialog [aria-current=page]').click();await page.locator('[data-section=understand]').click();await page.waitForSelector('[data-stage="understand"]:visible');assert.equal(await page.locator('#outline-dialog').isVisible(),false);await page.goBack();await page.waitForSelector('[data-stage="read"]:visible');
 await page.evaluate(()=>{window.SpeechSynthesisUtterance=class{constructor(text){this.text=text;}};speechSynthesis.getVoices=()=>[{lang:'tr-TR',name:'Test synthetic voice'}];speechSynthesis.speak=u=>{window.lastUtterance={text:u.text,lang:u.lang,rate:u.rate};u.onstart?.();u.onend?.();};});await page.selectOption('#course-rate','0.8');await page.locator('[data-play="0"]').click();assert.equal(await page.evaluate(()=>lastUtterance.lang),'tr-TR');assert.equal(await page.evaluate(()=>lastUtterance.rate),0.8);await page.locator('[data-stop]').click();assert.match(await page.locator('#course-audio-status').innerText(),/Stopped/);await page.evaluate(()=>speechSynthesis.getVoices=()=>[]);await page.locator('[data-play="0"]').click();assert.match(await page.locator('#course-audio-status').innerText(),/No Turkish synthetic voice/);await page.locator('.inline-word').first().click();await page.locator('#word-inspector [data-speech]').click();assert.match(await page.locator('#word-audio-status').innerText(),/No Turkish synthetic voice/);await page.keyboard.press('Escape');await page.evaluate(()=>Object.defineProperty(window,'speechSynthesis',{value:undefined,configurable:true}));await page.locator('[data-play="0"]').click();assert.match(await page.locator('#course-audio-status').innerText(),/unavailable/);await visit('lesson/ch5-2/read');await page.locator('#speak-prayer-btn').click();assert.match(await page.locator('#global-audio-status').innerText(),/unavailable/);assert(await page.locator('#global-audio-status').isVisible());await page.reload();
 for(const width of [360,390,768,1440]){await page.setViewportSize({width,height:900});for(const l of ['en','ko']){await lang(l);for(const id of ids)for(const stage of ['read','understand','practise','use']){await lesson(id,stage);assert(await page.locator(`[data-stage="${stage}"]`).first().isVisible());assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${width}/${l}/${id}/${stage} overflow`);}for(const p of ['home','learn','words','bible','practice','settings',...legacy.map(id=>`lesson/${id}/read`)]){await visit(p);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${width}/${l}/${p} overflow`);}console.log(`No overflow: ${width}px/${l}, all stages and workshops.`);}}
 await page.setViewportSize({width:1440,height:1000});await lang('ko');await lesson('prayer-illness','understand');const explanation=page.locator('[data-stage=understand] details.prerequisites');await explanation.locator('summary').press('Enter');assert.equal(await explanation.evaluate(e=>e.open),true);await explanation.locator('summary').press('Enter');assert.equal(await explanation.evaluate(e=>e.open),false);await page.evaluate(()=>document.body.style.zoom='2');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'200% zoom overflow');await page.evaluate(()=>document.body.style.zoom='');
 const dir=process.env.SCREENSHOT_DIR;if(dir){fs.mkdirSync(dir,{recursive:true});await visit('home');await lang('en');await page.screenshot({path:path.join(dir,'redesign-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await lang('ko');await lesson('ministry-04');await page.screenshot({path:path.join(dir,'redesign-phone-ko.png'),fullPage:false});}
 assert.deepEqual(errors,[],'Unexpected browser errors');assert.deepEqual(missing,[],'Missing assets');console.log('PASS: 77 lessons, 82 reading routes, 24 workshops, EN/KO, four widths, completion, backups, migration, review, prayer drafts, keyboard, TTS and fallback.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
